//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 VisionLocalization.rc 使用
//
#define IDC_ET_CALIBRATION_DPI_Y        0
#define IDC_BTN_RESET                   3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VISIONLOCALIZATION_DIALOG   102
#define IDD_MATCHVIEW_DIALOG            104
#define IDD_CScreenShotDlg              105
#define IDR_MAINFRAME                   128
#define IDD_MAKE_FEATURE                129
#define IDD_MOLD                        131
#define IDD_CALIBRATOR                  133
#define IDD_DLG_CALIBRATOR              133
#define IDD_DLG_TEMP                    139
#define IDD_DLG_CAMERA                  143
#define IDD_TEMPLATE_DIALOG             149
#define IDD_PARAM_DIALOG                150
#define IDI_ICON                        152
#define IDD_STEP_DIALOG                 154
#define IDB_BITMAP1                     157
#define IDB_BITMAP_BG                   157
#define IDI_SETTING_BTN_ICON            158
#define IDI_CALIBRATION_BTN_ICON        159
#define IDI_COLLECT_BTN_ICON            160
#define IDI_LOADING_BTN_ICON            161
#define IDI_MODEL_BTN_ICON              162
#define IDI_PRINT_BTN_ICON              163
#define IDI_SAVE_BTN_ICON               164
#define IDI_MAX_ICON                    165
#define IDD_MAKE_TEMPMASK_DIALOG        166
#define IDI_ADD_ICON                    168
#define IDI_SELECTCUT_ICON              169
#define IDD_MAKE_TEMPLATE_DIALOG        170
#define IDC_CURSOR_ROTATE               172
#define IDC_CURSOR_ROTATING             173
#define IDI_NEW_TEMP_ICON               174
#define IDB_EXIT_FOCUS                  175
#define IDB_EXIT_NORMAL                 176
#define IDB_MAX_FOCUS                   177
#define IDB_MAX_NORMAL                  178
#define IDB_MIN_FOCUS                   179
#define IDB_MIN_NORMAL                  180
#define IDB_RESTORE_FOCUS               181
#define IDB_BITMAP9                     182
#define IDB_RESTORE_NORMAL              182
#define IDC_ST_VIDEO                    1002
#define IDC_BT_VIDEO                    1003
#define IDC_ET_ZOOM                     1005
#define IDC_ET_TOP                      1006
#define IDC_ET_BOTTOM                   1007
#define IDC_ET_LEFT                     1008
#define IDC_ET_RIGHT                    1009
#define IDC_ET_ROTATE                   1010
#define IDC_BT_LOAD_MOLD                1011
#define IDC_VIDEO_BT_ZOOM               1012
#define IDC_BT_MAKE_FEATURE             1013
#define IDC_BT_MAIN_FEATURE             1013
#define IDC_ST_GARY                     1014
#define IDC_EDIT1                       1015
#define IDC_FEATURE_ET_X                1015
#define IDC_MOLD_ET_X                   1015
#define IDC_ET_HIS_TH                   1015
#define IDC_ET_CALIBRATION_K_X          1015
#define IDC_ET_PADDING_FRAME_IN_LINE    1015
#define IDC_ET_CALIBRATION_ASSESSMENT   1015
#define IDC_EDIT_MASK                   1015
#define IDC_EDIT_FILENAME               1015
#define IDC_EDIT_NAME                   1015
#define IDC_EDIT2                       1016
#define IDC_FEATURE_ET_Y                1016
#define IDC_MOLD_ET_Y                   1016
#define IDC_ET_CALIBRATION_K_Y          1016
#define IDC_ET_PADDING_IM_WIDE          1016
#define IDC_ET_PADDING_DIR_INPUT        1016
#define IDC_ET_MAIN_CAMERA_PARAM        1016
#define IDC_EDT_PRODUCT                 1016
#define IDC_EDIT3                       1017
#define IDC_FEATURE_ET_W                1017
#define IDC_MOLD_ET_W                   1017
#define IDC_ET_P_DPI_X2                 1017
#define IDC_ET_CALIBRATION_DPI_X        1017
#define IDC_ET_PADDING_TH               1017
#define IDC_EDIT_TEMPLATE               1017
#define IDC_EDIT_SETTING_FOLDER         1017
#define IDC_EDIT4                       1018
#define IDC_FEATURE_ET_H                1018
#define IDC_MOLD_ET_H                   1018
#define IDC_ET_CALIBRATION_A_X          1018
#define IDC_ET_PADDING_ERODE            1018
#define IDC_ET_MAIN_TIFF                1018
#define IDC_EDT_SCORE                   1018
#define IDC_EDIT_SETTING_CCF_FILE       1018
#define IDC_EDIT5                       1019
#define IDC_FEATURE_ET_A                1019
#define IDC_MOLD_ET_S                   1019
#define IDC_ET_C_PASS_PIX               1019
#define IDC_ET_CALIBRATION_PASS         1019
#define IDC_ET_PADDING_DILATE           1019
#define IDC_ET_MAIN_CALIBRATOR          1019
#define IDC_EDT_OFFSET_X                1019
#define IDC_FEATURE_BT_ZOOM             1020
#define IDC_ET_P_DPI_Y2                 1020
#define IDC_ET_C_PASS_MM                1020
#define IDC_ET_CALIBRATION_DIST_X       1020
#define IDC_ET_PADDING_DENSITY          1020
#define IDC_EDT_OFFSET_Y                1020
#define IDC_FEATURE_ET_S                1021
#define IDC_MOLD_ST_MOLD                1021
#define IDC_ET_D_P                      1021
#define IDC_ET_D_X2                     1021
#define IDC_ET_CALIBRATION_DIST_Y       1021
#define IDC_ET_PADDING_GAUSSIAN         1021
#define IDC_EDT_PRINT_SPEED             1021
#define IDC_MOLD_ST_CONTRAST            1022
#define IDC_ET_IM_X                     1022
#define IDC_ET_CALIBRATION_A_Y          1022
#define IDC_ET_MAIN_WIDTH               1022
#define IDC_EDIT10                      1022
#define IDC_ET_CALIBRATION_TYPE         1022
#define IDC_EDT_PRINT_HEI               1022
#define IDC_MOLD_LOAD                   1023
#define IDC_ET_IM_Y                     1023
#define IDC_ET_MAIN_HEIGHT              1023
#define IDC_EDT_LIGHT                   1023
#define IDC_BT_SAVE                     1024
#define IDC_ET_D_Y2                     1024
#define IDC_EDT_NAME                    1024
#define IDC_BT_RECOVER                  1025
#define IDC_ET_SCAL_FACTOR_PRODUCT      1025
#define IDC_EDT_MAX_OVER_LAP            1025
#define IDC_BT_OK                       1026
#define IDC_ET_SCAL_FACTOR_CAMERA       1026
#define IDC_EDT_IMAGE                   1026
#define IDC_EDT_FEATURE                 1027
#define IDC_ET_ALPHA                    1030
#define IDC_ET_CALIBRATION_CHART_ROWS   1030
#define IDC_BT_RESET                    1031
#define IDC_ET_CALIBRATION_CHART_COLS   1031
#define IDC_BT_SAVE_RANGE               1032
#define IDC_ET_CALIBRATION_DPI_ROWS     1032
#define IDC_MOLD_BT_RESET               1033
#define IDC_ET_CALIBRATION_DPI_COLS     1033
#define IDC_MOLD_BT_SAVE_RANGE          1034
#define IDC_MOLD_BT_SAVE                1035
#define IDC_ET_CALIBRATION_DIST_ROWS    1035
#define IDC_MOLD_BT_RECOVER             1036
#define IDC_ET_CALIBRATION_DIST_COLS    1036
#define IDC_TEMP_ET_X                   1037
#define IDC_ET_CALIBRATION_AREA_ROWS    1037
#define IDC_EDIT7                       1038
#define IDC_TEMP_ET_Y                   1038
#define IDC_ET_PADDING_BLOCK            1038
#define IDC_EDIT6                       1039
#define IDC_ET_TEMP_SAME                1039
#define IDC_ET_PADDING_STRIDE           1039
#define IDC_BUTTON1                     1040
#define IDC_BT_SYNC_OS                  1040
#define IDC_BT_PRESCAN                  1040
#define IDC_BT_TEMP_LOAD_TIF            1040
#define IDC_BT_CALIBRATION_PRINT_CALIBRATION_IMAGE 1040
#define IDC_BT_MAIN_TIFF2               1040
#define IDC_BT_MAIN_PRINT               1040
#define IDC_BUTTON_CREATE               1040
#define IDC_BTN_SYS_PARAM               1040
#define IDC_BTN_CHOOSE                  1040
#define IDC_BUTTON_OK                   1040
#define IDC_BTN_AUTO_POSITION           1040
#define IDC_BT_CALIBRATOR               1041
#define IDC_BT_CONFIG                   1041
#define IDC_BT_MAIN_TIFF                1041
#define IDC_ET_CALIBRATION_AREA_COLS    1041
#define IDC_BUTTON_DELETE               1041
#define IDC_BUTTON5                     1041
#define IDC_BUTTON_CANCEL               1041
#define IDC_BUTTON3                     1042
#define IDC_BT_MAIN_CONFIG              1042
#define IDC_BT_PADDING_K_HOR_DECREASE   1042
#define IDC_BT_CALIBRATOR_FREEZE        1042
#define IDC_BUTTON_SAVE                 1042
#define IDC_BUTTON6                     1042
#define IDC_BUTTON_SETTING_FOLDER       1042
#define IDC_BUTTON4                     1043
#define IDC_BT_PADDING_K_VER_INCREASE   1043
#define IDC_BT_CALIBRATION_PARAM        1043
#define IDC_BTN_MATCH_CHECK             1043
#define IDC_BUTTON9                     1043
#define IDC_BUTTON_SETTING_CCF          1043
#define IDC_BT_PADDING_K_VER_DECREASE   1044
#define IDC_TEMP_MAX_BUTTON             1044
#define IDC_BUTTON_APPLY                1044
#define IDC_ST_CAL_VIEW                 1045
#define IDC_BT_CAMERA                   1046
#define IDC_CH_MES                      1047
#define IDC_BT_FEATURE_PARAM            1047
#define IDC_CH_MES2                     1048
#define IDC_BT_PRINTER                  1053
#define IDC_BT_TEMP_LOAD_CONFIG         1056
#define IDC_BT_TEMP_USE_CONFIG          1057
#define IDC_BT_TEMP_SAVE_CONFIG         1058
#define IDC_BT_CALIBRATION_CAMERA_CALIBRATION 1059
#define IDC_BT_CALIBRATION_SAVE         1060
#define IDC_CH_CALIBRATION_PASS         1061
#define IDC_CH_CALIBRATION_K            1062
#define IDC_CH_CALIBRATION_DPI          1063
#define IDC_BT_CALIBRATION_PRINT        1064
#define IDC_BT_CALIBRATION_PRINT2       1064
#define IDC_BT_MAIN_CAMERA              1065
#define IDC_BT_MAIN_CONNECT             1065
#define IDC_CB_MAIN_CAMERA              1066
#define IDC_BUTTON7                     1067
#define IDC_BT_MAIN_TEMP                1067
#define IDC_BUTTON8                     1068
#define IDC_BT_MAIN_CAMERA_PARAM        1068
#define IDC_BT_MAIN_CALIBRATOR          1069
#define IDC_BT_CALIBRATION_SCAN         1070
#define IDC_CB_MAIN_BOARD               1070
#define IDC_CH_PADDING_HISTOGRAM        1071
#define IDC_BT_MAIN_DISCONNECT          1071
#define IDC_BT_PADDING_FOREGROUND       1073
#define IDC_BT_PADDING_REFERENCE_POSITION 1074
#define IDC_ET_PADDING_REFERENCE_X      1075
#define IDC_ET_PADDING_REFERENCE_Y      1076
#define IDC_BT_PADDING_IMAGE_MERGING    1077
#define IDC_ET_PADDING_REFERENCE_W      1078
#define IDC_ET_PADDING_REFERENCE_H      1079
#define IDC_ET_PADDING_IM_FRAME_H       1080
#define IDC_ET_PADDING_IM_FRAME_H1      1080
#define IDC_ET_PADDING_IM_FRAME_W       1081
#define IDC_ET_PADDING_IM_FRAME_W1      1081
#define IDC_BT_PADDING_ROI              1082
#define IDC_ET_PADDING_IM_FRAME_H3      1082
#define IDC_BT_PADDING_PRESPECTIVE      1083
#define IDC_BT_PADDING_DPI              1084
#define IDC_BT_PADDING_HOMOGRAPHY       1085
#define IDC_BT_PADDING_DIR_INPUT        1086
#define IDC_BT_PADDING_IMAGE_MERGING2   1087
#define IDC_ET_PADDING_DIR_OUTPUT       1088
#define IDC_BT_PADDING_DIR_OUTPUT       1089
#define IDC_ET_PADDING_SKIP             1090
#define IDC_ET_PADDING_IM_FRAME_H2      1090
#define IDC_BT_PADDING_IMAGE_ALIGNING   1091
#define IDC_BT_PADDING_K                1092
#define IDC_ET_PADDING_IM_FRAME_W2      1092
#define IDC_ET_PADDING_K_HOR            1093
#define IDC_ET_PADDING_K_VER            1094
#define IDC_BT_PADDING_K_HOR_INCREASE   1095
#define IDC_BT_CALIBRATION_GEN          1096
#define IDC_ET_PADDING_A_HOR            1097
#define IDC_ET_PADDING_A_VER            1098
#define IDC_ET_PADDING_CAL_W            1099
#define IDC_ET_PADDING_CAL_H            1100
#define IDC_ET_PADDING_CAL_L            1101
#define IDC_ET_PADDING_CAL_T            1102
#define IDC_BT_PADDING_REFRESH          1103
#define IDC_ET_PADDING_DIR_CACHE        1107
#define IDC_BT_PADDING_DIR_CACHE        1108
#define IDC_BT_MAIN_PRINTER             1109
#define IDC_EDIT8                       1110
#define IDC_ET_MAIN_PRINT               1110
#define IDC_ET_CALIBRATOR_FRAME         1110
#define IDC_BT_MAIN_GATHER              1110
#define IDC_EDIT9                       1111
#define IDC_ET_MAIN_FEATURE             1111
#define IDC_ET_PADDING_PASS_IN_STRIDE   1111
#define IDC_BT_MAIN_GATHER2             1111
#define IDC_BT_MAIN_SAVEBACKGROUND      1111
#define IDC_BT_MAIN_MAKE_FEATURE        1112
#define IDC_BT_CALIBRATOR_CRAB          1113
#define IDC_BT_MAIN_CHANGE_FEATURE      1113
#define IDC_BT_MAIN_CAPTURE_IMAGE       1113
#define IDC_ET_CALIBRATION_DPI_ROWS2    1114
#define IDC_BT_MAIN_CUT_IMAGE           1114
#define IDC_ET_CALIBRATION_DPI_COLS2    1115
#define IDC_BT_MAIN_GATHER3             1115
#define IDC_BT_MAIN_NEWTEMP             1115
#define IDC_ET_CALIBRATION_SCALE_VER    1116
#define IDC_ET_CALIBRATION_QENCODE_LEFT 1117
#define IDC_ET_CALIBRATION_SCALE_HOR    1117
#define IDC_BT_CALIBRATION_QENCODE      1120
#define IDC_ET_PADDING_DIR_PARAM        1121
#define IDC_BUTTON2                     1122
#define IDC_BT_PADDING_DIR_PARAM        1122
#define IDC_BTN_MASK_CHOOSE             1122
#define IDC_BTN_ROTATE_INC              1122
#define IDC_BTN_TEMP_CHOOSE             1123
#define IDC_BTN_ROTATE_DEC              1123
#define IDC_COMBO2                      1124
#define IDC_CB_MAIN_MODEL               1124
#define IDC_BTN_PRODUCT_CHOOSE          1124
#define IDC_BTN_SCALE_INC               1124
#define IDC_BTN_MASK_DEL                1125
#define IDC_BTN_SCALE_DEC               1125
#define IDC_BTN_IMAGE_CHOOSE            1126
#define IDC_BTN_MOVE_UP                 1126
#define IDC_BTN_MASK_MAKE               1127
#define IDC_BTN_MOVE_LEFT               1127
#define IDC_STATIC_DISTANCE             1128
#define IDC_BTN_TEMPLATE_MAKE           1128
#define IDC_BTN_MOVE_DOWN               1128
#define IDC_STATIC_CARSPEED             1129
#define IDC_BTN_MOVE_RIGHT              1129
#define IDC_STATIC_VOLTAGE              1130
#define IDC_ET_FEATURE_DISTANCE2        1130
#define IDC_PIC_IMAGE                   1131
#define IDC_SLIDER                      1133
#define IDC_PROGRESS_                   1136
#define IDC_PROGRESS_PRINT              1136
#define IDC_TEMPLATE_LIST               1141
#define IDC_STATIC_IMAGE                1142
#define IDC_STATIC_TEMPLATE             1143
#define IDC_STATIC_TEMPLATE2            1144
#define IDC_STATIC_MASK                 1144
#define IDC_CHECK1                      1145
#define IDC_CHECK_SHAPE_MATCH           1145
#define IDC_CHECK_DEBUG                 1145
#define IDC_STATIC_CR                   1146
#define IDC_COMBO_LAYER                 1147
#define IDC_COMBO_SEARCH_TYPE           1148
#define IDC_SLIDER_                     1149
#define IDC_SLIDER_CONSTRAST_RATIO      1149
#define IDC_LIST_RESULT                 1150
#define IDC_STATIC_STEP                 1151
#define IDC_SPIN_FEATURE                1152
#define IDC_STATIC_TEMPLISTINFO         1153
#define IDC_COMBO1                      1154
#define IDC_COMBO3                      1155
#define IDC_EDIT_SETTING_CAMERA_PARAM   1156
#define IDC_CMB_MOVE_STEP               1156
#define IDC_EDIT_SETTING_CALIBRATOR_PARAM 1157
#define IDC_BUTTON_SETTING_CALIBRATOR_PARAM 1158
#define IDC_BUTTON_SETTING_CAMERA_PARAM 1159
#define IDC_CHECK_IMAGE_SHOW            1160
#define IDC_SLIDER_ALPHA                1161
#define IDC_BTN_MAKE                    1162
#define IDC_IMAGE_STATIC                1163
#define IDC_CMB_SCALE_STEP              1164
#define IDC_CMB_ROTATE_STEP             1165
#define IDC_CMB_SCALE                   1166
#define IDC_SLIDER_CONTRASTRatio        1167
#define IDC_SLIDER_CONTRAST_RATIO       1167
#define WM_RESET_TEMPLATE               2001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
